services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres_rise
    environment:
      - 'POSTGRES_DB=rise'
      - 'POSTGRES_PASSWORD=rise'
      - 'POSTGRES_USER=rise'
    ports:
      - '5432:5432'
  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: rabbitmq_rise
    environment:
      - 'RABBITMQ_DEFAULT_USER=rise'
      - 'RABBITMQ_DEFAULT_PASS=rise'
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: unless-stopped